Практика 3.2
Forsigg/dualboot-django-task-manager pull request #5
Opened 2022-10-14 15:50 UTC by Forsigg

Добавлены модели Tag, Task. В модель User добавлены роли

2022-10-14 18:37 UTC, Forsigg commented
К этому PR добавлены комиты для практики 3.4. Модели отображаются в админке (красиво, с полями), все миграции сохраняются внутри контейнера (добавлен волюм)

2022-10-18 20:40 UTC, aleksandr-semenov-dbp requested changes

2022-10-18 20:40 UTC, aleksandr-semenov-dbp commented on docker-compose.yml
> +      - .:/app
Нет, к сожалению, это неправильно, надо обойтись без такого волума

2022-10-18 20:40 UTC, aleksandr-semenov-dbp commented on docker-compose.yml
> +      && python manage.py migrate
миграции надо делать в процессе разработки руками, и хранить их в кодовой базе проекта. Дело в частности в том, что некоторые миграции пишутся руками а не создаются автоматически, и вся цепочка должна быть консистентна

2022-10-20 10:43 UTC, aleksandr-semenov-dbp requested changes

2022-10-20 10:43 UTC, aleksandr-semenov-dbp commented on main/models/task.py
> +class Task(models.Model):
после создания моделей надо сделать ./manage.py makemigrations и полученные файлы в main/migrations тоже должны попасть в коммит

2022-10-20 11:59 UTC, aleksandr-semenov-dbp approved these changes

2022-10-20 12:00 UTC, aleksandr-semenov-dbp approved these changes

2022-10-20 12:04 UTC, merged